name: deployment notification
on: [deployment_status]

jobs:
  successful_deploy:
    if: ${{ github.event.deployment_status.state == 'success' }}
    name: successful_deploy
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message when deploy is successfully done
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="🟢 ${{ github.event.deployment_status.description }}!"
      - name: set webhook for successful deploy
        run: |
          curl -s -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/setWebhook?url=https://babel-bot.vercel.app/api/index&allowed_updates=[\"message\"]&secret_token=${{ secrets.TELEGRAM_BOT_API_SECRET_TOKEN }}"
          echo "::set-output name=response::$response"
      - name: check webhook set and send notification
        run: |
          if echo "${{ steps.set_webhook.outputs.response }}" | grep -q '"ok":true'; then
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
              -d text="🟢 Webhook set successfully!"
          else
            curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
              -d text="🔴 Failed to set webhook: ${{ steps.set_webhook.outputs.response }}"          
  
  unsuccessful_deploy:
    if: ${{ github.event.deployment_status.state == 'failure' || github.event.deployment_status.state == 'error'}}
    name: unsuccessful_deploy
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message when deploy fails
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="🔴 ${{ github.event.deployment_status.description }}!\n📃 ${{ github.event.deployment_status.log_url }}"